services:

  baseimage:
    build: ./baseimage
    image: slurm-cluster/baseimage


  slurmjupyter:
    build: ./jupyter
    hostname: slurmjupyter
    user: admin
    volumes:
      - shared-vol:/home/admin
      - ./:/tmp/src
    ports:
      - 8888:8888

  slurmmaster:
    build: ./master
    depends_on:
      - baseimage
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
    ports:
      - 6817:6817
      - 6818:6818
      - 6819:6819

  slurmnode1:
    build: ./node
    hostname: slurmnode1
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
  slurmnode2:
    build: ./node
    hostname: slurmnode2
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
  slurmnode3:
    build: ./node
    hostname: slurmnode3
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
volumes:
  shared-vol:
